### PR TITLE
Updates to Covid Bot Instructions doc

### PR DESCRIPTION
**Pull request by rujabbar**
Incorporated the following updates from Stan related to instructions for:
1. Sending email notifications(using Logic Apps) when the Bot response does not meet the required confidence level
2. Using rich custom real-time queries in Power BI for querying logs in App Sights.

### CODE REVIEW

**Comment by Microsoft-Gov** [comment]
Pending group review.

**Comment by joesarabia** [comment]
Approval pending broader team review. On Hold.

**Comment by mphacker** [comment]
I am going to make a couple of minor changes to simplify the flow of the document.  I will be basing it off of this version of the document.  Let's not merge this version and I will push in the updated on shortly.

**Comment by joesarabia** [comment]
Sounds good! Closing this PR pending the submission of the next PR w/those updates.

**Pull request closed without merging**
